name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: luzisrepo
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris

          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          # Contributions calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: X

          # Music (Apple Music recent tracks)
          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_mode: recent
          plugin_music_limit: 2

          # Mastered technologies & topics
          plugin_topics: yes
          plugin_topics_limit: 60
          plugin_topics_mode: mastered
          plugin_topics_custom: python, javascript, html, css, jquery, discord.py, git, linux, bash, java, tensorflow, moviepy, react, tailwind, nextjs, typescript, react-native, jax, supabase, pytorch, docker, aws, rabbitmq, go, rust, processing, terraform, gymnasium, stablebaselines, fastapi, nestjs, nginx, ffmpeg, websockets, solidity, neovim
